Posix: avoid unused variable warning when preemption is disabled
Fixes:

FreeRTOS/FreeRTOS/Source/portable/ThirdParty/GCC/Posix/port.c: In function ‘vPortSystemTickHandler’:
FreeRTOS/FreeRTOS/Source/portable/ThirdParty/GCC/Posix/port.c:370:11: error: unused variable ‘pxThreadToResume’ [-Werror=unused-variable]
 Thread_t *pxThreadToResume;
           ^~~~~~~~~~~~~~~~