Posix: fix build failure
Fixes: a48f137896b9 ("Posix Port: Comment and remove unused variables (#230)")

The above commit introduced the compile error:

/FreeRTOS/FreeRTOS/Source/portable/ThirdParty/GCC/Posix/port.c: In function ‘prvSetupSignalsAndSchedulerPolicy’:
/FreeRTOS/FreeRTOS/Source/portable/ThirdParty/GCC/Posix/port.c:528:28: error: incompatible type for argument 3 of ‘pthread_sigmask’
                            *&xSchedulerOriginalSignalMask );
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/signal.h:359,
                 from FreeRTOS/FreeRTOS/Source/portable/ThirdParty/GCC/Posix/port.c:53:
/usr/include/x86_64-linux-gnu/bits/sigthread.h:33:31: note: expected ‘__sigset_t * restrict’ {aka ‘struct <anonymous> * restrict’} but argument is of type ‘sigset_t’ {aka ‘struct <anonymous>’}
        __sigset_t *__restrict __oldmask)__THROW;